{"name": "test_unsuccessful_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'AuthPage' object has no attribute 'equal'", "trace": "auth_page = <pom.index_page.AuthPage object at 0x000002A31A07A4D0>\n\n    @pytest.mark.api\n    def test_unsuccessful_login(auth_page):\n        auth_page.enter_uncorrect_username()\n        auth_page.enter_correct_password()\n        auth_page.click_login_button()\n>       auth_page.unsuccessful_login()\n\ntests\\test_auth.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pom.index_page.AuthPage object at 0x000002A31A07A4D0>\n\n    def unsuccessful_login(self):\n        expected_text = 'Epic sadface: Username and password do not match any user in this service'\n        actual_text = self.to_text('css', Locators.ERROR_MESSAGE)\n>       self.equal(expected_text, actual_text)\nE       AttributeError: 'AuthPage' object has no attribute 'equal'\n\npom\\index_page.py:39: AttributeError"}, "attachments": [{"name": "log", "source": "2c6899ce-5a0b-4624-ba30-866b87e1fd41-attachment.txt", "type": "text/plain"}], "start": 1666205298623, "stop": 1666205299395, "uuid": "e5ac4580-bd41-47dd-9e58-8dfdb50cd200", "historyId": "04f274e5324be96ce13f74f96034c8d3", "testCaseId": "29dceb981ec4792a3490629b226a0793", "fullName": "tests.test_auth#test_unsuccessful_login", "labels": [{"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "NB-100211"}, {"name": "thread", "value": "12156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}